version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-236-169-55.compute-1.amazonaws.com
            port: '5432'
            database: d6b9gsrnoh3or4
            ssl: true
            user: efblrmmiwvqkss
            password: 56b2f10c674cd9e8955c3ce8626b58533b07cc5d564c5343346a8126bb64393d
            migrations: true
